export const curData = [
    { htmlCode: '164', name: 'generic currency symbol' },
    { htmlCode: '36', name: 'dollar sign' },
    { htmlCode: '162', name: 'cent sign' },
    { htmlCode: '163', name: 'pound sterling' },
    { htmlCode: '165', name: 'yen symbol' },
    { htmlCode: '8355', name: 'franc sign' },
    { htmlCode: '8356', name: 'lira symbol' },
    { htmlCode: '8359', name: 'peseta sign' },
    { htmlCode: '8364', name: 'euro symbol' },
    { htmlCode: '8377', name: 'rupee symbol' },
    { htmlCode: '8361', name: 'won sign' },
    { htmlCode: '8372', name: 'hryvnia sign' },
    { htmlCode: '8367', name: 'drachma sign' },
    { htmlCode: '8366', name: 'tugrik sign' },
    { htmlCode: '8368', name: 'german penny sign' },
    { htmlCode: '8370', name: 'guarani sign' },
    { htmlCode: '8369', name: 'peso sign' },
    { htmlCode: '8371', name: 'austral sign' },
    { htmlCode: '8373', name: 'cedi sign' },
    { htmlCode: '8365', name: 'kip sign' },
    { htmlCode: '8362', name: 'new sheqel sign' },
    { htmlCode: '8363', name: 'dong sign' },
];